version: '3'
services:
    
  neo4j:
    image: neo4j:4.4.9-community
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7687:7687" # bolt protocol
      - "7474:7474" # http protocol
      - "7473:7473" # https protocol
    volumes:
      - ./db/data:/data
      - ./db/conf/:/conf/
      - ./db/import:/import
      - ./db/neo4j/logs:/logs
    restart: always
    environment:
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_apoc_import_file_enabled: true
      NEO4J_AUTH: neo4j/1234
