version: '3'
services:
    
  neo4j:
    image: neo4j:4.4.12-community
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7687:7687" # bolt protocol
      - "7474:7474" # http protocol
      - "7473:7473" # https protocol
    volumes:
      - ./db/data:/var/lib/neo4j/data
      - ./db/conf/:/var/lib/neo4j/conf
      - ./db/import:/var/lib/neo4j/import
      - ./db/neo4j/logs:/var/lib/neo4j/logs
    restart: always
    environment:
      NEO4J_AUTH: neo4j/5692132
      NEO4J_dbms_directories_import: import
      NEO4J_dbms_security_allow__csv__import__from__file__urls: true
      TZ: 'America/Sao_Paulo'
      NEO4J_dbms_memory_heap_initial__size: 3G
      NEO4J_dbms_memory_heap_max__size: 3G
      NEO4J_dbms_memory_pagecache_size: 13G

  api:
    build: .
    container_name: api
    command: src/api.py
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    depends_on:
      - neo4j